### ISSUE TITLE
Migrating repository to xarray-contrib

### ISSUE THREAD

**Issue by nicrie** [xarray-contrib/xeofs#142]
As suggested [here](https://github.com/pydata/xarray/pull/8561) by @dcherian there's the option to add xeofs to [xarray-contrib](https://github.com/xarray-contrib). Besides increased visibility, this could potentially attract more people willing to contribute to the further development of xeofs.

Do you have any objections to migrating xeofs to xarray-contrib, @slevang or are you in agreement with this?

**Comment by slevang** [comment]
Yeah sounds good to me!

**Comment by nicrie** [comment]
Opened an issue over in [xarray-contrib](https://github.com/xarray-contrib/xarray-contrib/issues/13).
