### ISSUE TITLE
Is the reconstruction of unseen data possible using EOF?

### ISSUE THREAD

**Issue by agirnow** [xarray-contrib/xeofs#156]
Hi, and thanks again for this great package !

This may be an idiot question, but I do not manage to consider this properly:

As far as I understand, transform method followed by inverse_transform should be able to retrieve the initial dataset whatever the components of the EOF are.

However, using this snippet of code it apperars that it is not true:
```
import xarray as xr
import pandas as pd
import numpy as np
import xeofs

lat = np.arange(-10, 11, 1) 
lon = np.arange(-20, 21, 1) 
time = pd.date_range("2020-01-01", periods=30, freq="D")
time2 = pd.date_range("2020-02-01", periods=30, freq="D")


# Create random data
data_y = np.random.rand(len(lat), len(lon), len(time))
data_y2 = np.random.rand(len(lat), len(lon), len(time2))

# Create xarray datasets
y = xr.DataArray(data_y, coords=[("latitude", lat), ("longitude", lon), ("time", time)])
y2 = xr.DataArray(data_y2, coords=[("latitude", lat), ("longitude", lon), ("time", time2)])


# MCA apply
eof = xeofs.models.EOF(30)
eof.fit(y-y.mean("time"),dim="time")
scores = eof.transform(y2-y2.mean("time"),normalized=False)
print(np.abs(eof.inverse_transform(scores,normalized=False)-(y2-y2.mean("time"))).mean())
```
The final line computes the average between the initial dataset and the reconstruction, so I would expect the result to be close to 0, especially because i consider a large number of modes, but it is not. 
Can anyone help? Sorry if this comes from a misunderstanding from my side.
Thanks a lot,
Alexandre

**Comment by slevang** [comment]
I wonder if this is just because you're using purely random data and the SVD solve is poor. Or something to do with the dimensionality of the arrays you've chosen. I have code doing exactly this with real data and it works well. Using the mock array from the test suite, which has some coherent signal plus noise, and more samples than features:

```python
import xarray as xr
import pandas as pd
import numpy as np
import xeofs

def mock_data_array(n):
    rng = np.random.default_rng(n)
    noise = rng.normal(5, 3, size=(25, 5, 4))
    signal = 2 * np.sin(np.linspace(0, 2 * np.pi, 25))[:, None, None]
    return xr.DataArray(
        signal + noise,
        dims=("time", "lat", "lon"),
        coords={
            "time": xr.date_range("2001", "2025", freq="YS"),
            "lat": [20.0, 30.0, 40.0, 50.0, 60.0],
            "lon": [-10.0, 0.0, 10.0, 20.0],
        },
        name="t2m",
        attrs=dict(description="mock_data"),
    )

y = mock_data_array(1)
y2 = mock_data_array(2)

eof = xeofs.models.EOF(20)
eof.fit(y, dim="time")
y2_recon = eof.inverse_transform(eof.transform(y2))
np.abs(y2_recon - y2).mean().item()

3.977485008022086e-15
```

**Comment by slevang** [comment]
As an aside it would be nice to have an option like `n_modes="all"`, which figures out the rank of the data early on and sets `n_modes = rank`. When I want to do experiments like this I usually just first try to fit the model with a million modes and then get the rank from the error message and plug it in.

Looks like sklearn.PCA does this as a [default](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html): `n_components = None`

**Comment by slevang** [comment]
Experimented a little more, it's just the dimensionality of the dataset you're using. You need `n_samples>=n_features` such that the rank of the SVD is at least `n_features` to get a perfect reconstruction. So if you increase the time dimension (and `n_modes`) to 861 in your example above, you get the expected result.

**Comment by agirnow** [comment]
Thanks everyone ! Indeed, I did not think about the fact that for non-squared matrix, decomposition is limited by the rank of the matrix, which is not sufficient to explain all the variability (especially for random values). It is more clear now.
