### ISSUE TITLE
Trouble creating the eof object

### ISSUE THREAD

**Issue by MahdiHasanNCSU** [xarray-contrib/xeofs#164]
Today,  installed xeofs and tried to perform a test run of the package.

Although I think I have successfully installed the package, I am unable to create the EOF object.
I used the commands from Website's Quickstart link and are as follows:

import xeofs as xe
model = xe.models.EOF()

Error Message:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 model = xe.models.EOF()

TypeError: __init__() missing 1 required positional argument: 'X'

**Comment by nicrie** [comment]
Hey @MahdiHasanNCSU thank you for raising this issue. Which version of `xeofs` are you using? 
If you're using a conda environment, you can check the version using
```bash
conda list xeofs
```
Alternatively, within Python you can use
```py
from xeofs import __version__
print(__version__)
```

**Comment by MahdiHasanNCSU** [comment]
# Name                    Version                   Build  Channel
xeofs                     0.7.2              pyhd8ed1ab_0    conda-forge

**Comment by MahdiHasanNCSU** [comment]
xeofs    0.7.2

**Comment by nicrie** [comment]
In that case please update to the most recent version, which is `v2.3.2`. Then your issue should be gone. Please let me know if it worked.

With conda, the following should work:
```bash
conda update xeofs
```

**Comment by MahdiHasanNCSU** [comment]
Thanks @nicrie. For some reason,  xeofs is not updating. 'conda update xeofs' runs without any issue, but I see the same version 0.7.2.

**Comment by MahdiHasanNCSU** [comment]
Since this is an issue on my end, I will see if I can figure it out. But, you are welcome to give any suggestions.

**Comment by nicrie** [comment]
Did you try installing in a fresh environment? The only reason I can think of right now is that some other packages in that environment prevent updating you to a more recent version of `xarray`. `xeofs` requires at least `xarray` version `2023.01`.

**Comment by MahdiHasanNCSU** [comment]
That's exactly what I was thinking. I believe that the updated version of xeofs also requires Python version >= 3.10.
I will update my status. I appreciate your active engagement.

**Comment by MahdiHasanNCSU** [comment]
The issue is resolved after creating a new environment with updated package versions. Appreciate your help!
