### ISSUE TITLE
Repository rights to change settings

### ISSUE THREAD

**Issue by nicrie** [xarray-contrib/xeofs#189]
Since moving xeofs to xarray-contrib, I no longer have the rights to change the repository settings. 

I'm working on a minor release that adds 5 new model classes to the API. The problem is that right now, we can only merge PRs using "squash and merge"  which means: either I need to make a separate PR for each model (which would create 5 minor releases) or combine everything into one commit, but that would lose detail in the documentation/changelog.

Ideally, I'd like to push to a develop branch and then do a regular merge commit.

@Slevang, do you have the rights to enable "merge commit" for this repo?

**Comment by slevang** [comment]
5 models, you're on a role!

I don't have any access at all to the repo `Settings` it looks like. One of the `xarray-contrib` owners might be able to expand our permissions.

Alternatively, could you tag your 5 PRs with anything other than `feat:` so they don't trigger a release, and then add one final PR tagged `feat:`?

**Comment by nicrie** [comment]
Yeah, that would work, though the new models wouldn't be listed as new features in the CHANGELOG - admittedly just a cosmetic detail. 😉

@andersy005, could you help out here real quick? If you as a xarray-contrib owner have the settings permissions for xeofs, could you enable "create a merge commit" as a PR option in addition to "squash & merge"? Thanks a lot!

**Comment by andersy005** [comment]
👋🏽 @nicrie, i just updated the repo settings and gave @xarray-contrib/xeofs-devs upgraded permissions. are you able to access and change repo settings?

**Comment by nicrie** [comment]
works! thank you @andersy005 ! :)
