### ISSUE TITLE
JOSS submission

### ISSUE THREAD

**Issue by nicrie** [xarray-contrib/xeofs#97]
hey Contributors @slevang  @aaronspring 

I've drafted some lines for a JOSS submission. Do you think you could [take a look at it](https://github.com/nicrie/xeofs/blob/joss-submission/publication/paper.md) in the next few days and give me some feedback? You can find the compiled paper [here](https://github.com/nicrie/xeofs/actions/runs/6696087288). Also, I'm not quite sure about your current affiliations, maybe you could just add those in yourselves? Thanks a lot and have a great week! :)

**Comment by slevang** [comment]
Nice, and thanks for the inclusion! I found a few typos and such but overall this looks good. Would you like me to add changes straight to the branch, or want to open a PR for easier commenting?

**Comment by aaronspring** [comment]
Hi niclas, thanks for the message but please take me from the authors list. I only contributed one line of readme code. Yours is all the effort and credit!

**Comment by nicrie** [comment]
Thanks to both of you for your quick feedback! 

@aaronspring Thanks Aaron! 

@slevang Of course! Feel free to add your changes straight to the branch (you should've received an invitation)

**Comment by nicrie** [comment]
just as info, I made some minor updates to the manuscript @slevang

**Comment by slevang** [comment]
I fixed a couple tiny typos and added an author affiliation.

Same as Aaron, it is completely unnecessary to put my name on this since the package is 99.99% your work. But if you want a coauthor, I have no problem with that either.

**Comment by nicrie** [comment]
Cool! :) you made a PR, fixed a bug and proposed features to improve the package, it think its only fair. More than happy to have you as a co author.

**Comment by nicrie** [comment]
I've submitted the package & it's currently under [pre-review](https://github.com/openjournals/joss-reviews/issues/6009).

**Comment by nicrie** [comment]
For the record: the paper has been published [here](https://joss.theoj.org/papers/10.21105/joss.06060).
